FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Service-Registry-0.0.1-SNAPSHOT.jar /home/Service-Registry-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Service-Registry-0.0.1-SNAPSHOT.jar"]