spring.application.name=PURCHASE-SERVICE
spring.profiles.active=prod
razorpay.key_id=rzp_test_26r2nPdExKatLW
razorpay.key_secret=jxiTKIbQD567iU3ky71ZNxmF
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
