FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/RoleAndPermissionService-0.0.1-SNAPSHOT.jar /home/RoleAndPermissionService-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/RoleAndPermissionService-0.0.1-SNAPSHOT.jar"]