FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Payroll-service-0.0.1-SNAPSHOT.jar /home/Payroll-service-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Payroll-service-0.0.1-SNAPSHOT.jar"]