FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Expense-Service-0.0.1-SNAPSHOT.jar /home/Expense-Service-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Expense-Service-0.0.1-SNAPSHOT.jar"]