FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Plan-Service-0.0.1-SNAPSHOT.jar /home/Plan-Service-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Plan-Service-0.0.1-SNAPSHOT.jar"]