FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/notice-0.0.1-SNAPSHOT.jar /home/notice-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/notice-0.0.1-SNAPSHOT.jar"]