FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Leave-Management-0.0.1-SNAPSHOT.jar /home/Leave-Management-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Leave-Management-0.0.1-SNAPSHOT.jar"]