FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Purchase-Service-0.0.1-SNAPSHOT.jar /home/Purchase-Service-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Purchase-Service-0.0.1-SNAPSHOT.jar"]