FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Holiday-Service-0.0.1-SNAPSHOT.jar /home/Holiday-Service-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Holiday-Service-0.0.1-SNAPSHOT.jar"]