FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/Api-Gateway-0.0.1-SNAPSHOT.jar /home/Api-Gateway-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/Api-Gateway-0.0.1-SNAPSHOT.jar"]