
#spring.datasource.url=jdbc:mysql://194.163.183.69:3306/papaya_hrms
#spring.datasource.username=papaya_hrms
#spring.datasource.password=h5rXEdN5iMB45rHS
spring.datasource.url=jdbc:mysql://docker.papayacoders.com:3306/hrms
spring.datasource.username=papaya_hrms
spring.datasource.password=papaya_hrms

server.port=8093

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload-dir=uploads/
eureka.client.serviceUrl.defaultZone=http://194.163.183.69:8761/eureka/
base.url=http://194.163.183.69:8080

spring.jackson.serialization.write-dates-as-timestamps=false
