FROM openjdk:17-jdk-slim-buster
LABEL maintainer="dwivedianuj9118@gmail.com"
COPY ./target/EventManagement-0.0.1-SNAPSHOT.jar /home/EventManagement-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/home/EventManagement-0.0.1-SNAPSHOT.jar"]